# docker-compose.yml

version: "3"
services:
    mechmarket-notifier:
        image: mechmarket-notifier
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./.env
